version: '3.8'
services:
  code-server:
    image: registry.nferx.com/nferx-developer/code-server:v1.0
    container_name: code-server-${USER}
    privileged: true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
      - PUSER=${USER}
      # - PASSWORD=password #optional
      # - HASHED_PASSWORD= #optional
      # - SUDO_PASSWORD=password #optional
      # - SUDO_PASSWORD_HASH= #optional
      # - PROXY_DOMAIN=code-server.my.domain #optional
      # - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - ./code-server/config:/config
      - /home/${USER}:/config/workspace
    ports:
      - 8448:8443